# Generated by Django 4.0 on 2021-12-28 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=255, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('embed', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('link', models.URLField()),
                ('image', models.URLField()),
                ('added', models.DateField(auto_now_add=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoria')),
            ],
        ),
    ]
